services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./internal/services/user/store/dynamodb/terraform:/terraform/"
      - "./.docker/localstack-terraform.py:/etc/localstack/init/ready.d/localstack-terraform.sh"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodb,iam,sts
      - LOCALSTACK_HOST=localstack
      - DYNAMODB_SHARE_DB=1
      - EXTENSION_AUTO_INSTALL=localstack-extension-terraform-init
      - DEBUG=1
    ports:
      - "4566:4566" # LocalStack Gateway
      #- "4510-4559:4510-4599" # External services port range
